// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NPC_Creator&Deleter","status":true,"description":"v1.0 - Plugin to create and delete NPCs on the current map. Currently can auto-create one NPC and as many as you want manually.","parameters":{"defaultNPCName":"NPC","allowMultipleNPCs":"true","autoCreateEnabled":"true","autoCreateMapId":"1","autoCreateX":"5","autoCreateY":"3","autoCreateDialogue":"Welcome to the game!\\nI'm an NPC!\\nTalk to me anytime!","autoCreateCharacter":"People1","autoCreateCharacterIndex":"0"}}
];
