// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"iPhone","status":true,"description":"v1.0 Adds a GTA-Style iPhone interface to the game.","parameters":{"iOSVersion":"26"}}
];
