// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MoralAlignment","status":true,"description":"v1.0 Moral Alignment (MZ)","parameters":{"MoralAlignment":"true","enableDebug":"true"}}
];
