// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MyPluginTemplate","status":true,"description":"v1.0 Example plugin template showing parameters and commands (MZ)","parameters":{"greetingText":"Hello from the plugin!","startingGold":"100","enableDebug":"true"}},
{"name":"SelfSwitchDefaults","status":true,"description":"Self Switch Defaults v0.2.0 - Allows you to set self switches \"ON\" by default.","parameters":{"storedSwitchMin":"19"}}
];
