// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MultiplayerMZ","status":true,"description":"v1.0 A plugin that facilitates multiplayer in RPG Maker MZ.","parameters":{"backendServerUrl":"http://localhost:3000","enableDebug":"true"}}
];
