// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SuperCoolPlugin","status":false,"description":"v1.0 Syncs real world and ingame time MZ)","parameters":{"RWTimeSync":"true","enableDebug":"true"}},
{"name":"RWWeatherSync","status":true,"description":"v1.2 Syncs real world time + weather.gov forecast to in-game (fixed for MZ)","parameters":{"RWTimeSync":"true","RWWeatherSync":"true","weatherUrl":"https://api.weather.gov/gridpoints/CTP/112,24/forecast","weatherVarId":"12","showWeatherMessage":"true","applyScreenWeather":"false","weatherPower":"4","weatherDuration":"60","enableDebug":"true\r\n\r\n------------------------------------------\r\nCOMMANDS\r\n------------------------------------------"}}
];
