// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MyPluginTemplate","status":true,"description":"v1.0 Example plugin template showing parameters and commands (MZ)","parameters":{"greetingText":"Hello from the plugin!","startingGold":"1000","enableDebug":"true"}}
];
